Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

AllCops:
  Exclude:
    - 'db/schema.rb'
